Add Eatery test to check certain fields always have a value
cuappdev/integration pull request #15
Opened 2019-10-09 22:04 UTC by seancorc

- **Context**: Prior to these changes there was only a "eateries on campus query" in the eatery test suite.

- **Changes:** Added two tests (a query for both campus and collegetown eateries) to check that the fields which should always have a value indeed do.

2019-10-09 22:09 UTC, meganle requested changes

2019-10-09 22:09 UTC, meganle commented on src/eatery/tests.py
> +    campust_eateries = response["data"]["campusEateries"]
`campus_eateries` instead?

2019-10-09 22:09 UTC, meganle commented on src/eatery/tests.py
> +		ratingEnum
indentation?

2019-10-09 22:09 UTC, meganle commented on src/eatery/tests.py
> +    campust_eateries = response["data"]["collegetownEateries"]
same as above?

2019-10-09 22:11 UTC, young-k commented on src/eatery/tests.py
> +    slug
minor, but prefer alphabetizing all of these fields

2019-10-09 22:11 UTC, young-k commented on src/eatery/tests.py
> +    for field in campust_eateries:
`return campus_eateries.all()` should suffice

2019-10-10 06:21 UTC, kq-li approved these changes
lgtm!

2019-10-10 06:21 UTC, kq-li commented on src/eatery/tests.py
> +    campusArea{
space before brace

2019-10-17 01:57 UTC, meganle approved these changes
nice job!

2019-10-17 04:03 UTC, merged